In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:16pt;}
div.text_cell_render.rendered_html{font-size:16pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:16pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:16pt;padding:5px;}
table.dataframe{font-size:16px;}
</style>
"""))

# <b><font size="7" color="red">ch11. 데이터프레임과 시리즈</font></b>
- pip install pandas
# 1장 판다스 패키지
- 데이터 분석을 위해 반드시 알아야 할 패키지. 넘파이를 기반으로 하며,
  다른 많은 라이브러리와 잘 통합되도록 설계
- 2차원 구조를 갖는 데이터프레임, 1차원 구조를 갖는 시리즈를 제공
- 판다스 장점 : 데이터프레임생성, 파일io, 레이블링, 부분데이터 추출,
  크기변경(행이나 열 삽입, 삭제), 데이터 분할, 병합, 데이터구조변경, 결측치 처리
  
- https://pypi.python.org/pypi/pandas(package index)
- http://pandas.pydata.org/pandas-docs/stable/api.html(API reference)

In [2]:
import pandas as pd
pd.__version__

'1.5.3'

In [4]:
data = pd.read_json('data/ch09_member1.json', encoding='cp949')
display(data)

name  age    email address
0  신길동   30  s@s.com      서울
1  김길동   20  a@s.com      수원
2  홍길동   10  d@s.com      부산

In [5]:
member4 = pd.read_csv('data/ch09_member4.csv')
display(member4)

name  age    email address
0  신길동   30  s@s.com      서울
1  김길동   20  a@s.com      수원
2  홍길동   10  d@s.com      부산

In [7]:
member1 = pd.read_csv('data/ch09_member1.csv', header=None, names=['name','age','email','address]'])
member1

name  age             email  address]
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구

# 2장 데이터프레임 만들기
## 2.1 딕셔너리 리스트를 이용해서 데이터 프레임 만들기

In [8]:
d = [{'kor':100,'mat':97},{'kor':90, 'mat':30}]
df = pd.DataFrame(data=d)
df

kor  mat
0  100   97
1   90   30

In [9]:
df.to_dict() # 데이터프레임을 딕셔너리로

{'kor': {0: 100, 1: 90}, 'mat': {0: 97, 1: 30}}

In [10]:
df.to_numpy() # 데이터프레임을 넘파이배열
df.valus # 위와 동일

array([[100,  97],
       [ 90,  30]], dtype=int64)

In [11]:
df.dtypes # 열의 타입

kor    int64
mat    int64
dtype: object

In [12]:
df.info() # ★

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      int64
dtypes: int64(2)
memory usage: 160.0 bytes


In [13]:
# 타입변경(열마다)
import numpy as np
df['kor'].astype(np.float64)
df['kor'] = df['kor'].astype('float64') # kor열의 타입을 float64로

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   kor     2 non-null      float64
 1   mat     2 non-null      int64  
dtypes: float64(1), int64(1)
memory usage: 160.0 bytes


In [15]:
d = [{'kor':100,'mat':97},{'kor':90, 'mat':30},{'kor':92, 'eng':70}]
df = pd.DataFrame(data=d)
df

kor   mat   eng
0  100  97.0   NaN
1   90  30.0   NaN
2   92   NaN  70.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   kor     3 non-null      int64  
 1   mat     2 non-null      float64
 2   eng     1 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 200.0 bytes


In [17]:
type(np.nan) # np.nan 결측치

float

In [18]:
df['kor'] = df['kor'].astype('int32')
df

kor   mat   eng
0  100  97.0   NaN
1   90  30.0   NaN
2   92   NaN  70.0

In [ ]:
# 결측치는 int로 형변환 불가(결측치를 대체값으로 치환 후 변환)
# df['mat'] = df['mat'].astype('int32')

## 2.2 리스트를 이용해서 데이터프레임 만들기

In [19]:
kor = [100,90,95,90,56]
mat = [99,100,40,89,79]
df = pd.DataFrame({'kor':kor, 'mat':mat})
df.head(2) # 상위 2행만

kor  mat
0  100   99
1   90  100

In [20]:
np.c_[kor, mat]

array([[100,  99],
       [ 90, 100],
       [ 95,  40],
       [ 90,  89],
       [ 56,  79]])

In [23]:
df = pd.DataFrame(data=np.c_[kor, mat], columns=['국어','수학'])
df

국어   수학
0  100   99
1   90  100
2   95   40
3   90   89
4   56   79

In [24]:
l = [['트렌드 코리아2026', '김난도', 10000, 10],
     ['사탄탱고', '라슬로', 17820, 10],
     ['미술관 여행자', '카미유주노', 29700, 10]]
df = pd.DataFrame(l, columns=['책이름', '저자', '가격', '할인율'])
df

책이름     저자     가격  할인율
0  트렌드 코리아2026    김난도  10000   10
1         사탄탱고    라슬로  17820   10
2      미술관 여행자  카미유주노  29700   10

In [26]:
%ls "c:/taro/ai/downlload/shareData/상가정보"

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: A014-DCD6

 c:\taro\ai\downlload\shareData\상가정보 디렉터리

2025-10-12  오후 03:33    <DIR>          .
2025-10-12  오후 03:33    <DIR>          ..
2025-04-27  오후 11:07             1,011 [필독]파일열람방법.txt
2025-04-27  오후 11:07        61,227,944 소상공인시장진흥공단_상가(상권)정보_강원_202503.csv
2025-04-27  오후 11:07       356,572,082 소상공인시장진흥공단_상가(상권)정보_경기_202503.csv
2025-04-27  오후 11:07        93,472,559 소상공인시장진흥공단_상가(상권)정보_경남_202503.csv
2025-04-27  오후 11:07        76,425,275 소상공인시장진흥공단_상가(상권)정보_경북_202503.csv
2025-04-27  오후 11:07        40,070,868 소상공인시장진흥공단_상가(상권)정보_광주_202503.csv
2025-04-27  오후 11:07        61,715,005 소상공인시장진흥공단_상가(상권)정보_대구_202503.csv
2025-04-27  오후 11:07        41,491,092 소상공인시장진흥공단_상가(상권)정보_대전_202503.csv
2025-04-27  오후 11:07        84,550,600 소상공인시장진흥공단_상가(상권)정보_부산_202503.csv
2025-04-27  오후 11:07       294,549,483 소상공인시장진흥공단_상가(상권)정보_서울_202503.csv
2025-04-27  오후 11:07         9,303,432 소상공인시장진흥공단_상가(상권)정보_세종_202503.csv
2025-04-27  오후 11:07        28,457,489 소상공인시

In [27]:
df = pd.read_csv('c:/taro/ai/downlload/shareData/상가정보/소상공인시장진흥공단_상가(상권)정보_서울_202503.csv',
                nrows=70) # 처음 70형만 가져오기
df.shape

(70, 39)

In [28]:
# 판다스 디스플레이 읍션
pd.options.display.max_columns = 39 # 39열까지 디스플레이 가능. 기본값은 20
pd.options.display.max_rows = 70 # 70행까지 디스플레이 가능. 기본값은 60

In [30]:
df.head(1).T

0
상가업소번호          MA010120220800000033
상호명                         부동산임대김은숙
지점명                              NaN
상권업종대분류코드                         I2
상권업종대분류명                          음식
상권업종중분류코드                       I212
상권업종중분류명                       비알코올 
상권업종소분류코드                     I21201
상권업종소분류명                          카페
표준산업분류코드                      I56229
표준산업분류명                 기타 비알코올 음료점업
시도코드                              11
시도명                            서울특별시
시군구코드                          11110
시군구명                             종로구
행정동코드                       11110540
행정동명                             삼청동
법정동코드                     1111014000
법정동명                             삼청동
지번코드             1111014000100280021
대지구분코드                             1
대지구분명                             대지
지번본번지                             28
지번부번지                           21.0
지번주소             서울특별시 종로구 삼청동 28-21
도로명코드                   111103100007
도로명                    서울특별시 종로구 삼청로
건물본번지                            122
건물부번지                            1.0
건물관리번호     1111014000100280021026727
건물명                              NaN
도로명주소            서울특별시 종로구 삼청로 122-1
구우편번호                         110230
신우편번호                           3053
동정보                              NaN
층정보                              NaN
호정보                              NaN
경도                         126.98184
위도                          37.58625

## 2.3 read_csv

In [31]:
# pd.read_csv() #함수 안에서 shift+tab+tab
pd.read_csv?

In [34]:
# (1) CSV 파일 불러오기(기본값)
member = pd.read_csv('data/ch11_member.csv')
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     6 non-null      object
 1   Age      6 non-null      int64 
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: int64(1), object(4)
memory usage: 368.0+ bytes


In [37]:
# 문자형으로 읽어들인 Birth를 datetime형으로
# 형변환 : astype('int64'), astype('datetime64')
#            to_datetime() 함수
# member['Birth'].astype('datetime64')
member['Birth'] = pd.to_datetime(member['Birth'])
member.head(1)

Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

In [38]:
member['Age'] = member['Age'].astype(np.int16)
member.dtypes

Name               object
Age                 int16
Email              object
Address            object
Birth      datetime64[ns]
dtype: object

In [41]:
# (2) 특정행을 제외하고 csv 파일 읽어오기
member = pd.read_csv('data/ch11_membercp949.csv', encoding='cp949',
                    skiprows=[1,6]) # 1,6번째 행 제외하고 읽어오기(시작은 1부터)
member

Name  Age         Email  Address       Birth
0  홍길서   30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남   21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북   22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중   23  mid@hong.com   부산시 중구  1999-01-30

In [43]:
# (3) 상위몇행만 sep문자는 , 아닌 csv파일 읽어오기
member = pd.read_csv('data/ch11_membersep.csv', 
                     nrows=5, # 상위 5행만
                     sep='|')
member

Name  Age          Email  Address       Birth
0  홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구  1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구  1999-01-30

In [44]:
# (4) 주석(#)제외, datetime형 필드를 지정하여 csv 파일 읽어오기
member = pd.read_csv('data/ch11_membertab.csv', sep='\t',
                     comment='#', # 주석제외
                    parse_dates=['Birth']) # datetime64형으로 읽어올 필드 지정
member

Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

## 2.4 패키지에서 가져오기 : irus 데이터
- iris 가져오기 방법1 : sklearn(머신러닝 패키지)
- iris 가져오기 방법2 : statsmodels(R 데이터)
- iris 가져오기 방법3 : seaborn(시각화패키지)
### 2.4.1 iris 방법 1 : sklearn
- sklearn.darasets 모듈 데이터(iris)를 데이터 프레임으로 변환

In [47]:
from sklearn import datasets # 머신러닝을 공부하기 위한 학습 데이터셋 제공
# sklearn 패키지에서 제공되는 데이터셋은 딕셔너리 형식으로 제공
iris = datasets.load_iris()
iris # Bunch타입(딕셔너리를 상속받은 타입) 딕셔너리처럼 동작
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [48]:
iris.data # 독립변수
iris['data'][:3] # 상위 3행

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [49]:
# 데이터프레임의 열이름(비추)
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [51]:
# 데이터프레임의 열이름(강추)
[col[:-5].replace(' ','_') for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [52]:
iris.target # ML/DL 학습시 타겟변수(종속변수)
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [53]:
iris.target_names[iris.target] # 데이터프레임에 쓸 타겟변수(가장 오른쪽 열)

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [55]:
# 독립변수
data = iris.data
# 종속변수
target = iris.target_names[iris.target].reshape(-1,1)
print(data[:3], target[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]] [['setosa']
 ['setosa']
 ['setosa']]


In [56]:
print('독립변수 shape :', data.shape)
print('타겟변수 shape :', target.shape)

독립변수 shape : (150, 4)
타겟변수 shape : (150, 1)


In [57]:
# 1. 독립변수와 종속변수를 stack한 후 데이터 프레임으로
df = pd.DataFrame(np.hstack((data, target)),
                 columns=iris.feature_names + ['specles'])
df

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)  \
0                 5.1              3.5               1.4              0.2   
1                 4.9              3.0               1.4              0.2   
2                 4.7              3.2               1.3              0.2   
3                 4.6              3.1               1.5              0.2   
4                 5.0              3.6               1.4              0.2   
..                ...              ...               ...              ...   
145               6.7              3.0               5.2              2.3   
146               6.3              2.5               5.0              1.9   
147               6.5              3.0               5.2              2.0   
148               6.2              3.4               5.4              2.3   
149               5.9              3.0               5.1              1.8   

       specles  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [58]:
df.columns = [col[:-5].replace(' ','_') for col in iris.feature_names] + ['specles']
df.head(1)

sepal_length sepal_width petal_length petal_width specles
0          5.1         3.5          1.4         0.2  setosa

In [59]:
# 2. 독립변수, 종속변수를 따로 데이터프레임으로 생성 -> 두 데이터프레임을 연결
X = pd.DataFrame(iris.data, columns = [col[:-5].replace(' ','_') for col in iris.feature_names])
X.head(1)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2

In [61]:
y = pd.DataFrame(iris.target_names[iris.target], columns=['specles'])
y.head(1)

specles
0  setosa

In [62]:
print('X의 shape :', X.shape)
print('y의 shape :', y.shape)
print('X의 index :', X.index)
print('y의 index :', y.index)

X의 shape : (150, 4)
y의 shape : (150, 1)
X의 index : RangeIndex(start=0, stop=150, step=1)
y의 index : RangeIndex(start=0, stop=150, step=1)


In [63]:
iris_df = pd.concat((X,y), axis=1) # 두개의 데이터프레임을 열로 연결
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   specles       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
